name: immutable_ordered_map
description: A dart implementation of Immutable ordered map
version: 1.0.0
repository: https://github.com/flutter-cavalry/immutable_ordered_map

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  mgenware_dart_lints: ^4.1.0
  test: ^1.24.0
